### ISSUE TITLE
crashed everytime i hit upload button

### ISSUE THREAD

**Issue by hoductan** [vancer0/guu#1]
first of all, thanks to you for making this thing. im a mac user and i kinda struggle every time i want to upload something (it take more time than usual). All i want is create an new torrent on gt.ru. the rest i can do it manually. hope you can fix it soon
<img width="763" alt="Ảnh chụp Màn hình 2022-09-01 lúc 02 30 34" src="https://user-images.githubusercontent.com/106651892/187766461-ef264667-813c-46fa-b7fa-8aecd0ab8728.png">
<img width="528" alt="Ảnh chụp Màn hình 2022-09-01 lúc 02 32 49" src="https://user-images.githubusercontent.com/106651892/187766551-8d602654-5fb0-4f95-b2c8-b9be941eec21.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/106651892/187766669-ad3dbb7b-dcd9-4759-991d-76eee254e1e6.png">

**Comment by vancer0** [comment]
Hello, thanks for the report!
The issue will be fixed in the next version (3). Keep an eye on the [forum post](https://community.gaytorrent.ru/topic/59502/software-release-gaytor-rent-upload-utility) or the releases page to be notified.

**Comment by hoductan** [comment]
thank you so much. it works perfectly after the update
